name: Workflow

on:
  push:
    branches: [ Master ]

env:
  ENV: ${{ env.ENV_VAR }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [ dev, qa, prod ]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Environment
      if: $env == 'dev'
      run: echo "Building for dev environment"

    - name: Set Environment
      if: $env == 'qa'
      run: echo "Building for qa environment"

    - name: Set Environment
      if: $env == 'prod'
      run: echo "Building for prod environment"

    - name: Build Application
      run: echo "Building application"
