name: Workflow

on:
  push:
    branches: [ Master ]

env:
  ENV: dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [ qa, dev, prod ]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Environment
      run: echo "Building for ${{ env }} environment"

    - name: Build Application
      run: echo "Building application for ${{ env }} environment"